import MainLayout from "@/components/shared/layouts/main/MainLayout";
import StyledComponentsRegistry from "@/lib/RootStyleRegistry";
import MswProviders from "@/providers/MswProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        />
      </head>
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <MswProviders>
            <MainLayout>{children}</MainLayout>
          </MswProviders>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
