import MainLayout from "@/components/shared/layouts/main/MainLayout";
import StyledComponentsRegistry from "@/lib/RootStyleRegistry";
import MswProviders from "@/providers/MswProvider/MswProvider";
import QueryProvider from "@/providers/QueryProvider";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        />
      </head>
      <body>
        <StyledComponentsRegistry>
          <QueryProvider>
            <MswProviders>
              <MainLayout>{children}</MainLayout>
            </MswProviders>
          </QueryProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
